name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    if: "!contains(github.event.commits[0].message, 'chore(release): publish')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci && npm ci --workspaces=true
      - run: nom run prepare
      - run: npm run build
      - run: npm run test # should be unnecessary, but let's be sure!
      - name: Setup Git
        run: |
          git config --global user.email "dazn-bot@dazn.com"
          git config --global user.name "DAZN Bot"
      - run: npm run new-version
        env:
          GH_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.OSS_NPM_TOKEN }}
      - run: npm run publish
